
rule run_maxbin2:
    input:
        r1=expand("{wdir}/{sample}/{pre_processing}/R1.fastq.gz", pre_processing=config["pre_processing"], allow_missing=True),
        r2=expand("{wdir}/{sample}/{pre_processing}/R2.fastq.gz", pre_processing=config["pre_processing"], allow_missing=True),
        contig_path=expand("{wdir}/{sample}/{assembly}", assembly=config["assembly"], allow_missing=True)
    output:
        folder=directory("{wdir}/{sample}/maxbin2")
    threads: 5
    run:
        shell("mkdir -p {output.folder}")
        shell("run_MaxBin.pl -contig {input.contig_path}/contigs.fasta -reads {input.r1} -reads2 {input.r2} -thread {threads} -out {output.folder}/output")
