
rule run_metaspades:
    input:
        r1=expand("{wdir}/{sample}/{pre_metaspades}/R1.fastq.gz", wdir=config["WDIR"], sample=config["SAMPLES"], pre_metaspades=config["PRE_METASPADES"]),
        r2=expand("{wdir}/{sample}/{pre_metaspades}/R2.fastq.gz", wdir=config["WDIR"], sample=config["SAMPLES"], pre_metaspades=config["PRE_METASPADES"]),
    output:
        directory("{wdir}/{sample}/metaspades")
    threads: 10
    resources:
        mem_gb=45
    shell:
        """
        spades.py --meta --only-assembler -t {threads} -m {resources.mem_gb} -1 {input.r1} -2 {input.r2} -o {output}
        """
