
rule run_metagahit:
    input:
        r1=expand("{wdir}/{sample}/{pre_processing}/R1.fastq.gz", wdir=config["WDIR"], sample=config["SAMPLES"], pre_processing=config["pre_processing"]),
        r2=expand("{wdir}/{sample}/{pre_processing}/R2.fastq.gz", wdir=config["WDIR"], sample=config["SAMPLES"], pre_processing=config["pre_processing"]),
    output:
        directory("{wdir}/{sample}/megahit")
    threads: 10
    resources:
        mem_gb=45
    params:
        complex_metagenome="--presets meta-large"
    run:
        shell("megahit {params.complex_metagenome} -t {threads} -m 0.5 -1 {input.r1} -2 {input.r2} -o {output}")
        shell("mv {output}/final.contigs.fa {output}/contigs.fasta")
