
rule db_kaiju:
    params: "fungi"
    output:
        directory("{wdir}/kaijudb")
    run:
        shell("mkdir -p {output}")
        shell("cd {output} && kaiju-makedb -s {params}")


rule run_kaiju:
    input:
        r1=expand("{wdir}/{sample}/{pre_kaiju}/R1.fastq.gz", wdir=config["WDIR"], sample=config["SAMPLES"], pre_kaiju=config["PRE_KAIJU"]),
        r2=expand("{wdir}/{sample}/{pre_kaiju}/R2.fastq.gz", wdir=config["WDIR"], sample=config["SAMPLES"], pre_kaiju=config["PRE_KAIJU"]),
        kaijudb={rules.db_kaiju.output}
    output:
        fout="{wdir}/{sample}/kaiju/kaiju.out"
    threads: 5
    shell:
        """
        kaiju -v -t {input.kaijudb}/nodes.dmp -f {input.kaijudb}/{rules.db_kaiju.params}/kaiju_db_{rules.db_kaiju.params}.fmi \
        -z {threads} \
        -i {input.r1} -j {input.r2} \
        -o {output.fout}
        """
        