name: "Sphinx: Render docs"

on:
  push:
    branches:
      - "gh-pages"
    paths:
      - "docs/**"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python3 -m pip install -r ./requirements.txt

      - run: sphinx-build -M html source build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#     steps:
#     - uses: actions/checkout@v4
#     - uses: actions/setup-python@v5
#     - name: directly build sphinx
#         run: 
#           pip install -r requirements.txt
          
#     - name: Upload artifacts
#       uses: actions/upload-artifact@v4
#       with:
#         name: html-docs
#         path: docs/build/html/
#     - name: Deploy
#       uses: peaceiris/actions-gh-pages@v3
#       if: github.ref == 'refs/heads/main'
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: docs/build/html
